### PR TITLE
Feature/sql register

### PR DESCRIPTION
**Pull request by milos-colic**

### CODE REVIEW

**Review by sllynn — APPROVED** [review]
Looking good. Let's merge and I can try it out with e.g. Power BI.

**Comment by sllynn** [comment]
@tdiepenbrock-databricks I think this will enable your geoserver integration?

**Comment by milos-colic** [comment]
@sllynn I have change it a bit to have the codecov pass.
can you please re-review?

**Review by sllynn — COMMENTED** [review]
I'll throw in some little additions to the docs then you can merge if happy.

**Pull request merged**
