### PR TITLE
Feature/dbr warning

### PR DESCRIPTION
**Pull request by milos-colic**

### CODE REVIEW

**Comment by milos-colic** [comment]
@sllynn @mjohns-databricks we have a flaky test in JTS for union it sometimes returns a correct result other times it throws invalid geometry exception

**Review by mjohns-databricks — COMMENTED** [review]
Recommend MosaicContext checkDBR function include content similar to:

```
val dbrMajor = sparkVersion.split("-").head.split("\\.").head.toInt
if (
    (dbrMajor < 13 && mosaicVersion >= "0.4.0") ||
    (dbrMajor > 12 && mosaicVersion < "0.4.0")
) {
    logWarning("DEPRECATION WARNING: Mosaic v0.3.x series only supports Databricks Runtime 12 and below. You can specify `%pip install 'databricks-mosaic<0.4,>=0.3'` for DBR < 13.")
            
    println("DEPRECATION WARNING: Mosaic v0.3.x series only supports Databricks Runtime 12 and below. You can specify `%pip install 'databricks-mosaic<0.4,>=0.3'` for DBR < 13.")  
    false
} else if (!isML && !isPhoton && !isTest) {
    logWarning("DEPRECATION WARNING: Please use a Databricks Photon-enabled Runtime (for performance benefits) or Runtime ML (for spatial AI benefits). Mosaic will stop working on this cluster after v0.3.x.")
    
    println("DEPRECATION WARNING: Please use a Databricks Photon-enabled Runtime (for performance benefits) or Runtime ML (for spatial AI benefits). Mosaic will stop working on this cluster after v0.3.x.")
    false
} else {
    true
}
```

**Review by mjohns-databricks — APPROVED** [review]
lgtm

**Review by edurdevic — APPROVED** [review]
lgtm

**Pull request merged**
