### PR TITLE
Distance and area measurement functions

### PR DESCRIPTION
**Pull request by tdikland**
This contribution provides some easy-to-use methods for measuring distance and areas in km^2. The following methods are implemented:
- ST_HAVERSINE: Given two points represented by latitude/longitude in degrees, it will use the Haversine formula to calculate the great circle distance between them in kilometers. (assumes the Earth is spherical with radius 6371.0088 km)
- GRID_CELLAREA: Given a cell_id in a concrete grid index system, it calculates the area of the grid cell in km^2 using L’Huilier’s Formula. (assumes the Earth is spherical with radius 6371.0088 km)

### CODE REVIEW

**Comment by tdikland** [comment]
@milos-colic I wasn't entirely sure how to leverage the base abstractions for these functions. If possible, could you give me some pointers?

**Comment by milos-colic** [comment]
@tdikland let's catch up for 30 min and I can walk you through this.

**Review by milos-colic — APPROVED** [review]
@tdikland LGTM

**Review by milos-colic — APPROVED** [review]
LGTM

**Review by milos-colic — APPROVED** [review]
LGTM

**Comment by milos-colic** [comment]
Tests are passing and the code looks good, I will merge.

**Pull request merged**
