### PR TITLE
Bugfix for scala starter notebook.

### PR DESCRIPTION
**Pull request by sllynn**
Fixes incorrect reference to `optimal_resolution` in scala quickstart notebook

### CODE REVIEW

**Comment by milos-colic** [comment]
@sllynn is this intentionally only fixing a style of the variable? ie is the PR complete and ready for review?

**Comment by sllynn** [comment]
> @sllynn is this intentionally only fixing a style of the variable? ie is the PR complete and ready for review?

No, the notebook failed to run because the variable is declared using camel but quoted as snake in that cell.

**Review by milos-colic — APPROVED** [review]
Looks good to me.

**Comment by milos-colic** [comment]
@sllynn reviewed, happy for you to merge it.

**Pull request merged**
