### PR TITLE
Feature/fix raster to grid

### PR DESCRIPTION
**Pull request by milos-colic**

### CODE REVIEW

**Review by mjohns-databricks — APPROVED** [review]
lgtm

**Review by mjohns-databricks — APPROVED** [review]
lgtm

**Comment by milos-colic** [comment]
@sllynn @mjohns-databricks this is ready for review.
Code coverage is broken but it is only -0.17% which is likely just a couple of lines that were missed.

**Review by mjohns-databricks — APPROVED** [review]
lgtm

**Pull request merged**
