### PR TITLE
Aligned pypi release action to scala build

### PR DESCRIPTION
**Pull request by edurdevic**
The release action was not aligned with the scala build, it was missing a `sudo`.

### CODE REVIEW

**Review by mjohns-databricks — APPROVED** [review]
LTGM (on behalf of Milos)

**Comment by milos-colic** [comment]
@edurdevic  We can merge this even though the build fails. It fails since the python version contains "-SNAPSHOT" which expected since we are having versioning post release. This workflow should not run on snapshot PRs anyways so it wont fail in subsequent PRs. And it should run fine on release PRs.

**Review by milos-colic — APPROVED** [review]

**Comment by milos-colic** [comment]
And for the actual release we need to:
- merge this
- update version to v0.3.6 (or v0.3.7 - I dont really mind if one number is skipped)
- release 
- update version to next snapshot

**Comment by mjohns-databricks** [comment]
Merging, ref Milos note on slack.

**Pull request merged**
