### PR TITLE
Mjohns/gdal filetree

### PR DESCRIPTION
**Pull request by mjohns-databricks**
Initial PR to get 2 tarballs for gdal filetree plus init script. Delivery of the tarballs will most likely be worked into a separate PyPI deployed module (e.g. `databricks-mosaic-gdal`), so this is just the initial. Also, current Init Script usage will give way eventually to JVM based install since install is now just untar operations (vs apt installs).

Given the main tarball size (92MB) GitHub recommended Git Large File Storage which is good to know about:

> remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.

### CODE REVIEW

**Comment by milos-colic** [comment]
@mjohns-databricks I think we need a separate python module for these.
We dont want all mosaic jars to carry the tarballs.
Maven will bring into the jar anything in the resources dir.

**Comment by mjohns-databricks** [comment]
@milos-colic here is a first cut at adding under a (new) modules folder. Let me know what you think about this and if you have any recommended tweaks on the structure. Once finalized, we would then build as `databricks-mosaic-gdal` for pypi.org. I set initial version to 3.4.3 to mirror the gdal version. Would verify at https://test.pypi.org/ first to make sure all is good. Also, set license to MIT as the code falls under the included GDAL licensing (we are not adding any code, just packaging).

**Comment by mjohns-databricks** [comment]
@milos-colic here is the final identified change with the Databricks licenses instead of MIT. The local test (that approximates the init script style install from pypi) was successful, see notebook test [here](https://e2-demo-field-eng.cloud.databricks.com/?o=1444828305810485#notebook/145370659808571/command/3131765080060966). Recommend merging into main (it is under modules and not part of other build processes). Separately, I will add to pypi.org.

**Comment by mjohns-databricks** [comment]
Ah, well. pypi also wouldn't allow the > 100MB file (both databricks_mosaic_gdal-3.4.3-py3-none-any.whl and databricks-mosaic-gdal-3.4.3.tar.gz are 122MB). Not sure how to best package it to overcome the limit.

**Comment by mjohns-databricks** [comment]
@milos-colic I had some time to work on this some more and was able to swap gzip with xz compression and got everything down to ~70MB and got it into PyPI, see https://pypi.org/project/databricks-mosaic-gdal/3.4.3/ . There is a test of the init script from the pypi hosted package at https://e2-demo-field-eng.cloud.databricks.com/?o=1444828305810485#notebook/145370659808571. The init script takes ~20s to run, so not bad. This should be good now to merge to main (which will make the homepage link at pypi work).

**Review by milos-colic — APPROVED** [review]
LGTM

**Pull request merged**
