### PR TITLE
Feature/st buffer

### PR DESCRIPTION
**Pull request by milos-colic**
This is to replace #94 due to cumbersome rebase that caused too many changes to be reflected in the PR.
The PR adds the st_buffer functionality to mosaic API.

### CODE REVIEW

**Comment by milos-colic** [comment]
@tiems90 as per slack, this is the PR adding the logic for st_buffer.

**Review by sllynn — APPROVED** [review]
LGTM

**Comment by sllynn** [comment]
Still passing. Let's merge?

**Comment by milos-colic** [comment]
@sllynn will update the docs

**Comment by sllynn** [comment]
> @sllynn will update the docs

Docs are in.

**Pull request merged**
