### PR TITLE
Update the link to Sedona

### PR DESCRIPTION
**Pull request by bjornjorgensen**
Fix links to Sedona.

### CODE REVIEW

**Comment by milos-colic** [comment]
@bjornjorgensen We have now opened up the process for merging the external PRs.
Can you please confirm with the: https://github.com/databrickslabs/mosaic/blob/main/CONTRIBUTING.md?
After your PR is compliant, I am happy to review it and merge it if the review is successful.

**Comment by bjornjorgensen** [comment]
Signed-off-by: Bjørn Jørgensen <bjornjorgensen@email.com>

**Comment by bjornjorgensen** [comment]
I see they have released a new version https://sedona.apache.org/1.4.0/

**Review by milos-colic — APPROVED** [review]
LGTM.
Signoff confirmed.

**Comment by bjornjorgensen** [comment]
I found some more links that are not working 
On the github front page 
Documentation
Check out the documentation pages. <- link is dead 

About
An extension to the Apache Spark framework that allows easy and fast processing of very large geospatial datasets.

databrickslabs.github.io/mosaic/ <- wrong link

If you can give me the right links then I can update them in this PR?

**Comment by bjornjorgensen** [comment]
Returns the `resolution` grid index associated with the input `lng` and `lat` coordinates. -> lng == lon
https://github.com/databrickslabs/mosaic/blob/0aec1f89f125551fdf30a27f75159a0c3a32aefd/python/mosaic/api/functions.py#L1421

**Comment by milos-colic** [comment]
@bjornjorgensen 
https://databrickslabs.github.io/mosaic/ is working, see below:
Screenshot 2023-06-03 at 21 53 32

**Comment by milos-colic** [comment]
@bjornjorgensen I also tested the "Checkout documentation" link from Readme and that works as well.

**Comment by milos-colic** [comment]
@bjornjorgensen Since this is signed off and the new links for Sedona are correct I will merge this one.
Any link changes that are not concerned with Sedona can be provided in a separate PR.
Thank you for your contribution!

**Comment by bjornjorgensen** [comment]
Strange with the link 
I get this 
[Screenshot_20230603_230117.png](file:///home/bjorn/Pictures/Screenshot_20230603_230117.png)

**Comment by milos-colic** [comment]
It is probably your ISP that marks for some reason github as not trusted (probably github selfsigned the root certificate).
It basically depends on your internet provider. 
I had a similar issue with github last year with Vodafone and it resolved on its own.

**Pull request merged**
